WebApplication1/Controllers/AdminController.cs
using HealthFeed.Business.Repository.AdminRepo;
using HealthFeed.DataAccess;
using HealthFeed.Entity.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HealthFeedCpanel.Controllers
{
    public class AdminController : Controller
    {
        DataContext _context;
        public AdminController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        //  [HttpPost]
        //public ActionResult Index(string email, string password)
        //{
        //    var Rvalue = repository.Login(email, password);
        //    if (Rvalue)
        //    {

        //        return RedirectToAction("Index", "Home");
        //    }
        //    else
        //        ViewBag.success = false;
        //    return View();
        //}
        [HttpPost]
        public async Task<IActionResult> Index(AdminUser loginModel)
        {
            AdminRepository repository = new AdminRepository(_context);

            if (repository.Login(loginModel.Email, loginModel.Password))
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, loginModel.Email)
                };

                var userIdentity = new ClaimsIdentity(claims, "login");

                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);


                //Just redirect to our index after logging in. 
                return RedirectToAction("Index", "Home");
            }
            else
                ViewBag.success = false;
            return View();
        }

        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/PostsController.cs
using HealthFeed.DataAccess;
using HealthFeed.Entity.Models;
using HealthFeedCpanel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace HealthFeedCpanel.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly DataContext _context;

        public PostsController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewModel model = new ViewModel();
            model.Post = _context.Posts.ToList();
            model.Category = _context.Categories.ToList();
            return View(model);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Category)
                .Include(p => p.UrlParser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["UrlParserId"] = new SelectList(_context.UrlParsers, "Id", "Id");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategoryId,Title,Description,ImageUrl,PubDate,UrlParserId,IsActive")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", post.CategoryId);
            ViewData["UrlParserId"] = new SelectList(_context.UrlParsers, "Id", "Id", post.UrlParserId);
            return View(post);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", post.CategoryId);
            ViewData["UrlParserId"] = new SelectList(_context.UrlParsers, "Id", "Id", post.UrlParserId);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,CategoryId,Title,Description,ImageUrl,PubDate,UrlParserId,IsActive")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Category)
                .Include(p => p.UrlParser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult PostHeader()
        {
            return PartialView();
        }
        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
    }
}

WebApplication1/Controllers/UrlParsersController.cs
using HealthFeed.DataAccess;
using HealthFeed.Entity.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
namespace HealthFeedCpanel.Controllers
{
    public class UrlParsersController : Controller
    {
        private readonly DataContext _context;

        public UrlParsersController(DataContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View(_context.UrlParsers.ToList());
        }

        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var UrlParsers = await _context.UrlParsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (UrlParsers == null)
            {
                return NotFound();
            }

            return View(UrlParsers);
        }
        [HttpPost]
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: UrlParsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Creating([Bind("Id,Url,Title,Description,Image,ImageTag,RssRoad,PubDate")] UrlParser UrlParsers)
        {
                if (ModelState.IsValid)
                {
                    _context.Add(UrlParsers);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            return View(UrlParsers);
        }

        [HttpPost]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var UrlParsers = _context.UrlParsers.Find(id);
            if (UrlParsers == null)
            {
                return NotFound();
            }
            return PartialView(UrlParsers);
        }
        [Authorize]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editing(int id, [Bind("Id,Url,Title,Description,Image,ImageTag,RssRoad,PubDate")] UrlParser UrlParsers)
        {
            if (id != UrlParsers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(UrlParsers);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UrlParsersExists(UrlParsers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(UrlParsers);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                var UrlParsers = _context.UrlParsers.Find(id);
                _context.UrlParsers.Remove(UrlParsers);
                _context.SaveChanges();
                return Json(true);
            }

            catch (Exception)
            {
                return Json(false);
            }
        }

        private bool UrlParsersExists(int id)
        {
            return _context.UrlParsers.Any(e => e.Id == id);
        }
        public IActionResult UrlHeader()
        {
            return PartialView();
        }
    }
}

WebApplication1/Controllers/UserController.cs
using HealthFeed.DataAccess;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace HealthFeedCpanel.Controllers
{
    public class UserController : Controller
    {
        private DataContext context;
        public UserController(DataContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            return View(context.Users.ToList());
        }



        public IActionResult UserHeader()
        {
            return PartialView();
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Health Feed Control Panel</title>

    <link href="~/img/brand/favicon.png" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="~/js/plugins/nucleo/css/nucleo.css" rel="stylesheet" />
    <link href="~/js/plugins/fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link href="~/css/argon-dashboard.css" rel="stylesheet" />
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
        <div class="container-fluid">
            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Brand -->
            <a class="navbar-brand pt-0" href="@Url.Action("Index","Home")">
                <img src="~/logo.png" class="navbar-brand-img" alt="...">
            </a>
            <!-- User -->
            <ul class="nav align-items-center d-md-none">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                <img alt="Image placeholder" src="https://bootdey.com/img/Content/avatar/avatar6.png">
                            </span>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                        <div class="dropdown-divider"></div>
                        <a href="@Url.Action("LogOut","Admin")" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </li>
            </ul>
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Collapse header -->
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                        </div>
                        <div class="col-6 collapse-close">
                            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                                <span></span>
                                <span></span>
                            </button>
                        </div>
                    </div>
                </div>
                <!-- Form -->
                <!-- Navigation -->
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link active" asp-controller="Home" asp-action="Index">
                            <i class="ni ni-tv-2 text-primary"></i> Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-controller="UrlParsers" asp-action="Index">
                            <i class="ni ni-pin-3 text-orange"></i> Rss Links
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Posts" asp-action="Index">
                            <i class="ni ni-planet text-blue"></i> Posts
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-controller="User" asp-action="Index">
                            <i class="ni ni-single-02 text-yellow"></i> User profile
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-controller="CategoryAndBranch" asp-action="Index">
                            <i class="ni ni-caps-small text-green"></i> Category And Branch
                        </a>
                    </li>
                </ul>
                <!-- Divider -->
                <hr class="my-3">
                <!-- Heading -->
                <h6 class="navbar-heading text-muted">Documentation</h6>
                <!-- Navigation -->
            </div>
        </div>
    </nav>
    <div class="main-content">
        <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
            <div class="container-fluid">
                <!-- Brand -->
                <!-- Form -->
                <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
                    <div class="form-group mb-0">
                        <div @*class="input-group input-group-alternative" *@>
                        </div>
                    </div>
                </form>
                <!-- User -->
                <ul class="navbar-nav align-items-center d-none d-md-flex">
                    <li class="nav-item dropdown">
                        <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="media align-items-center">
                                <span class="avatar avatar-sm rounded-circle">
                                    <img alt="Image placeholder" src="https://bootdey.com/img/Content/avatar/avatar6.png">
                                </span>
                                <div class="media-body ml-2 d-none d-lg-block">
                                    <span class="mb-0 text-sm  font-weight-bold">Admin</span>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                            <div class="dropdown-divider"></div>
                            <a href="@Url.Action("LogOut","Admin")" class="dropdown-item">
                                <i class="ni ni-user-run"></i>
                                <span>Logout</span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; 2019 - Health Feed </p>
        </footer>
    </div>
    <!--   Core   -->
    <script src="~/js/plugins/jquery/dist/jquery.min.js"></script>
    @*<script language="javascript" type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>*@
    <script src="~/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
    <!--   Optional JS   -->
    <script src="~/js/plugins/chart.js/dist/Chart.min.js"></script>
    <script src="~/js/plugins/chart.js/dist/Chart.extension.js"></script>
    <!--   Argon JS   -->
    <script src="~/js/argon-dashboard.min.js?v=1.1.0"></script>
    <script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
    <script src="~/sweetalert2/sweetalert2.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

</body>
</html>